PYTHON=python3

all: help

help:
	echo "Call make run# where # can be [1,5]."

run1: task1.py
	$(PYTHON) task1.py

run2: task1.py
	$(PYTHON) task1.py

run3: task3.py
	$(PYTHON) task3.py

run4: task1.py
	$(PYTHON) task1.py

run5: task1.py
	$(PYTHON) task1.py