PYTHON=python3

all: help

help:
	echo "Call make run# where # can be [1,5]."

run1: task1.py
	$(PYTHON) task1.py

run2: task2.py
	$(PYTHON) task2.py

run3: task3.py
	$(PYTHON) task3.py

run4: task4.py
	$(PYTHON) task4.py

run5: task5_bonus.py
	$(PYTHON) task5_bonus.py