PYTHON=python3

all: help

help:
	echo "Call make run# where # can be [1,5]."

run1: task1.py
	$(PYTHON) task1.py

run2: task2.py
	$(PYTHON) task2.py

run3: task3.py
	$(PYTHON) task3.py

run4: task4.py
	$(PYTHON) task4.py

run5A: task5A.py
	$(PYTHON) task5A.py

run5B: task5B.py
	$(PYTHON) task5B.py

run6: task6.py
	$(PYTHON) task6.py

run7A: task7A.py
	$(PYTHON) task7A.py

run7B: task7B.py
	$(PYTHON) task7B.py